name: 'Show workflow trigger'
description: 'Prints what triggered this workflow'

runs:
  using: "composite"
  steps:
    - name: Print trigger info
      uses: actions/github-script@v7
      with:
        script: |
          const eventName = context.eventName;
          const actor = context.actor || 'unknown';  // Default to 'unknown' if actor is not defined
          let eventAction = 'N/A';

          // Determine the event action based on the event type
          if (eventName === 'pull_request') {
            eventAction = context.payload.action || 'N/A';
          } else if (eventName === 'pull_request_review') {
            eventAction = context.payload.review.state || 'N/A';
          } else if (eventName === 'workflow_dispatch') {
            eventAction = 'manual trigger';
          } else if (eventName === 'schedule') {
            eventAction = 'scheduled trigger';
          }
          gh_ref = context.ref || 'N/A';
          console.log(`The job was triggered by a ${eventName} event.`);
          console.log(`  - Event action:           ${eventAction}`);
          console.log(`  - Triggered by:           ${actor}`);
          console.log(`  - GH ref is:              ${gh_ref}`);
          console.log(`  - GH actor is:            ${context.actor}`);
          console.log(`  - GH triggering actor is: ${context.triggering_actor}`);
          console.log(`  - GH event is:            ${context.event}`);
          console.log(`  - GH workflow is:         ${context.workflow}`);
