name: SNL-AT2

on:
  # Runs on PRs against main
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
      # first, yes to these
      - '.github/workflows/at2_snl.yml'
      - 'src/mam4xx'
      - 'src/tests'
      - 'src/validation/**'
      # second, no to these
      - '!src/tests/data/**'
      # not sure whether this should be disabled--keep for now
      # - '!src/validation/mam_x_validation/**'

  # Manual run
  workflow_dispatch:

  # # Add schedule trigger for nightly runs at midnight MT (Standard Time)
  # schedule:
  #   - cron: '0 7 * * *'  # Runs at 7 AM UTC, which is midnight MT during Standard Time

concurrency:
  # Two runs are in the same group if they are testing the same git ref
  #  - if trigger=pull_request, the ref is refs/pull/<PR_NUMBER>/merge
  #  - for other triggers, the ref is the branch tested
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gcc-cuda:
    uses:
      ./.github/workflows/at2_gcc-cuda.yml
