name: "MAM4xx Autotester"

on:
  # Runs on PRs against main
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, ready_for_review, reopened]
    paths:
      # first, yes to these
      - '.github/workflows/*'
      - 'src/mam4xx/*'
      - 'src/tests/*'
      - 'src/validation/**'
      # second, no to these
      # don't test when it's only validation data changing
      - '!src/tests/data/**'
      # not sure whether this should be disabled--keep for now
      # - '!src/validation/mam_x_validation/**'

  # Manual run
  workflow_dispatch:
    inputs:
      architecture:
        description: 'Test Machine Architecture'
        required: true
        type: choice
        options:
          - GPU-NVIDIA_H100
          - CPU-Ubuntu_22-04
          - ALL

  # Add schedule trigger for nightly runs at midnight MT (Standard Time)
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC, which is midnight MT during Standard Time

concurrency:
  # Two runs are in the same group if they are testing the same git ref
  #  - if trigger=pull_request, the ref is refs/pull/<PR_NUMBER>/merge
  #  - for other triggers, the ref is the branch tested
  group: ${{ github.workflow }}-${{ github.ref }}${{ github.event.inputs.architecture }}
  cancel-in-progress: true

jobs:
  gcc-cuda:
    if: ${{ github.event.pull_request || github.event.schedule }}
    uses:
      ./.github/workflows/at2_gcc-cuda.yml
  gh_auto_test:
    if: ${{ github.event.pull_request || github.event.schedule }}
    uses:
      ./.github/workflows/gh_auto_test.yml
  clang-format_check:
    if: ${{ github.event.pull_request }}
    uses:
      ./.github/workflows/clang-format-check.yml
  manual-gpu_cuda:
    if: ${{ contains(github.event.inputs.architecture, 'GPU-NVIDIA_H100') ||
            contains(github.event.inputs.architecture, 'ALL') }}
    uses:
      "./.github/workflows/at2_gcc-cuda.yml"
  manual-cpu_gh:
    if: ${{ contains(github.event.inputs.architecture, 'CPU-Ubuntu_22-04') ||
            contains(github.event.inputs.architecture, 'ALL') }}
    uses:
      ./.github/workflows/gh_auto_test.yml
