name: PNNL Push Mirror
#test

on: [pull_request]

jobs:
  to_gitlab:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          # ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: ${{ secrets.GITLAB_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GITLAB_USER }}
          GIT_PASSWORD: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GIT_PUSH_ARGS: --push-option=ci.skip --tags --force --prune --verbose
          PUSH_ALL_REFS: "true"
          DEBUG: "true"
      - name: Trigger Pipeline
        # Need {{ github.head_ref }} for running within pull requests
        run: |
          curl -X POST -F token=${{ secrets.GITLAB_PIPELINE_TRIGGER_TOKEN }} -F ref=${{ github.head_ref }} https://code.pnnl.gov/api/v4/projects/298/trigger/pipeline
          exit $?
